### ISSUE TITLE
Unable to download from Available Downloads

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-media#156]
Steps to reproduce:
- Login using maha@mdv(org name is 'Media Viewer')
- Go to Media Viewer
- Click on 'Available Downloads'
- You will the error stating "<Message>The AWS Access Key Id you provided does not exist in our records.</Message>"

This is not happening in prod. Only on staging.

**Comment by mahalakshme** [comment]
@himeshr  @ashusvnath How come the zombie node process was not killed when redeploying avni-media code? Can the issue of old media code running after deploying new code occur again - it should not occur - this should also get fixed as part of this card - since this seems to be the rootcause of the issue.

**Comment by mahalakshme** [comment]
@vinayvenu would like to know the answer for above before closing this card.

**Comment by ashusvnath** [comment]
@mahalakshme We (@himeshr and I) have done a re-deploy to staging from CI and noticed that no zombie process was left after the deploy. This leaves us reasonably convinced that the zombie process was a 1-off occurrence. Possibly due to manual intervention with the environment. Not sure what else can be done to address this issue.
